### ISSUE TITLE
G285 Stuck in MASKROM

### ISSUE THREAD

**Issue by sicXnull** [NebraLtd/helium-bobcat-rk3566#8]
Any experience when the G285 gets stuck in MASKROM mode? Currently will not accept any flash for the bootloader. This seems to be a common issue for the G285 Bobcat. The G290/295 do not seem to be as susceptible. 

Erasing flash worked fine, Device is detected in MASKROM mode in both Windows and Linux

When attempting to flash the image in Rkdevtool (i’ve tried every version from 2.8-2.96) we get “Download Boot Fail”.

I’ve tried every usb port on multiple PCs, different USB cables. rkdeveloptool in Linux and all the same thing. This device appears to be bricked.

This has happened to multiple devices (i’m not the only one with this issue, just reporting it for a handful of people), so any help would be greatly appreciated. 

![image](https://github.com/NebraLtd/helium-bobcat-rk3566/assets/31908995/b0f88d0b-af6e-4815-9038-d0689fdd2473)

**Comment by adossa27** [comment]
I am having the same issue. It seems there is no bootloader

**Comment by sicXnull** [comment]
> I am having the same issue. It seems there is no bootloader

allegedly the bootloader is here, but the board will not accept it. 

https://dl.radxa.com/rock3/images/loader/rock-3a/rk356x_spl_loader_ddr1056_v1.10.111.bin

**Comment by Ldogg123** [comment]
Were you ever able to solve this? Having the same issue.

**Comment by sicXnull** [comment]
i'm closing this. We solved the issue. if interested join the Crankk discord.

**Comment by adossa27** [comment]
I was not ever able to solve it unfortunately
